# Pre-commit configuration for TrimX CLI Video Clipper
# Install with: pip install pre-commit && pre-commit install

repos:
  # Rust formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Rust-specific hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: rustfmt
        entry: cargo fmt --all --
        language: system
        pass_filenames: false
        always_run: true
        args: ["--", "--check"]
      
      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets --all-features --
        language: system
        pass_filenames: false
        always_run: true
        args: ["--", "-D", "warnings"]
      
      - id: cargo-check
        name: cargo check
        entry: cargo check --all-targets --all-features
        language: system
        pass_filenames: false
        always_run: true
      
      - id: cargo-test
        name: cargo test
        entry: cargo test --all-features
        language: system
        pass_filenames: false
        always_run: true
        args: ["--", "--nocapture"]

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

  # Documentation checks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types: [markdown, yaml, json]
        exclude: '^(.github/|docs/)'

  # Conventional commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # License header check
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        files: \.(rs|toml)$
        args:
          - --license-filepath
          - LICENSE_HEADER.txt
          - --comment-style
          - '//'
