#!/bin/bash
echo "=== Rust Installation Check ==="
echo "Rust version: $(rustc --version 2>/dev/null || echo 'Not found')"
echo "Cargo version: $(cargo --version 2>/dev/null || echo 'Not found')"
echo "Rust-analyzer: $(rust-analyzer --version 2>/dev/null || echo 'Not found')"
echo "PATH includes cargo: $(echo $PATH | grep -o '\.cargo/bin' || echo 'Not found')"
echo "Cargo bin directory: $(ls -la ~/.cargo/bin/ 2>/dev/null | head -3 || echo 'Directory not found')"
echo ""
echo "=== LaunchAgent Status ==="
launchctl list | grep com.rust.path || echo "LaunchAgent not found"
echo ""
echo "=== Environment Variables ==="
echo "HOME: $HOME"
echo "PATH: $PATH"
